export const PRODUCT_OPTIONS = [
  { slug: 'hoodie-zipper', name: "קפוצ'ון רוכסן", price: 85 },
  { slug: 'long-triko', name: 'טריקו ארוך', price: 60 },
  { slug: 'safety-helmet', name: 'קסדת בטיחות', price: 80 },
  { slug: 'vest-yellow', name: 'אפודה זוהרת צהובה', price: 45 },
  { slug: 'vest-orange', name: 'אפודה זוהרת כתומה', price: 45 },
  { slug: 'manager-vest-orange', name: 'אפודת מנהל כתומה', price: 100 },
  { slug: 'manager-vest-yellow', name: 'אפודת מנהל צהובה', price: 100 },
  { slug: 'hoodie-kenguru', name: "קפוצ'ון קנגורו", price: 85 },
  { slug: 'softshell-coat', name: 'מעיל סופטשל', price: 180 },
  { slug: 'drifit-short', name: 'חולצת דרייפיט קצרה', price: 50 },
  { slug: 'drifit-long', name: 'חולצת דרייפיט ארוכה', price: 55 },
  { slug: 'storm-suit', name: 'חליפת סערה', price: null },
  { slug: 'fleece-reversible', name: 'פליז דו צדדי', price: 190 },
  { slug: 'lab-coat', name: 'חלוק מעבדה', price: 90 },
  { slug: 'half-apron', name: 'סינר חצי', price: 100 },
  { slug: 'full-apron', name: 'סינר מלא', price: 120 },
  { slug: 'chef-jacket', name: "ז׳קט שף", price: 250 },
  { slug: 'drifit-stripes', name: 'חולצת דרייפיט עם פסים זוהרים', price: 80 },
  { slug: 'thermal-bottle', name: 'בקבוק תרמי', price: 49 },
  { slug: 'tshirt-short', name: 'טי-שירט קצרה', price: 55 },
  { slug: 'helmet-manager', name: 'קסדת מנהל', price: 80 },
  { slug: 'maatz-vest', name: 'אפודת מציל', price: 45 },
  { slug: 'cargo-pants', name: 'מכנסי קארגו', price: 60 },
  { slug: 'fleese-single', name: 'פליז צד אחד', price: 85 },
];
